# Generated by Django 4.0.5 on 2022-06-03 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=128)),
                ('collection_family', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('name_format', models.CharField(max_length=128)),
                ('image_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('royalty', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('royalty_address', models.CharField(max_length=128)),
                ('is_generated', models.BooleanField(default=False)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.blockchain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=128)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('chanse', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.layer')),
            ],
        ),
    ]
