# Generated by Django 4.0.5 on 2022-06-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_attribute_layer_layer_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user',
            new_name='creator',
        ),
    ]
