# Generated by Django 4.0.5 on 2022-06-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_rename_user_collection_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='chanse',
            new_name='chance',
        ),
    ]
